# Assignment 1
find b in the following using the least square equation to minimize.
<p align="center">
    <img src="https://latex.codecogs.com/gif.latex?%5Cdpi%7B150%7D%20%5Clarge%20%7C%7CAt-b%7C%7C%5E2"/>
</p>

## Q1.  
## find x and y.  
<p align="center">
    <img src="https://latex.codecogs.com/gif.latex?%5Cdpi%7B150%7D%20%5Clarge%20%5Cbegin%7Bbmatrix%7D%202%260%20%5C%5C%200%261%20%5C%5C%202%262%20%5Cend%7Bbmatrix%7D%20%5Cbegin%7Bbmatrix%7D%20x%5C%5C%20y%20%5Cend%7Bbmatrix%7D%20%3D%20%5Cbegin%7Bbmatrix%7D%201%20%5C%5C%202%20%5C%5C%203%20%5Cend%7Bbmatrix%7D"/>
</p>

## Q2.  
## find x, y and z.  
<p align="center">
    <img src="https://latex.codecogs.com/gif.latex?%5Cdpi%7B150%7D%20%5Clarge%20%5Cbegin%7Bbmatrix%7D%201%26-2%264%20%5C%5C%201%26-1%261%20%5C%5C%201%260%260%20%5C%5C%201%261%261%20%5C%5C%201%264%264%20%5Cend%7Bbmatrix%7D%20%5Cbegin%7Bbmatrix%7D%20x%5C%5C%20y%5C%5C%20z%5C%5C%20%5Cend%7Bbmatrix%7D%20%3D%20%5Cbegin%7Bbmatrix%7D%200%20%5C%5C%200%20%5C%5C%201%20%5C%5C%200%20%5C%5C%200%20%5C%5C%20%5Cend%7Bbmatrix%7D"/>
</p>

## Q3.  
## find x and y.  
<p align="center">
    <img src="https://latex.codecogs.com/gif.latex?%5Cdpi%7B150%7D%20%5Clarge%20%5Cbegin%7Bbmatrix%7D%203%26-6%20%5C%5C%204%26-8%20%5C%5C%200%261%20%5Cend%7Bbmatrix%7D%20%5Cbegin%7Bbmatrix%7D%20x%5C%5C%20y%20%5Cend%7Bbmatrix%7D%20%3D%20%5Cbegin%7Bbmatrix%7D%20-1%20%5C%5C%207%20%5C%5C%202%20%5Cend%7Bbmatrix%7D"/>
</p>

### this is solved using the following quation:
<p align="center">
    <img src="https://latex.codecogs.com/gif.latex?%5Cdpi%7B150%7D%20%5Clarge%20%28A%5E%7BT%7DA%29%5E%7B-1%7DA%5E%7BT%7Db"/>
</p>

In [2]:
import numpy as np

## Answer 1.

In [30]:
A = np.matrix([[2,0],[0,1],[2,2]])
b = np.matrix([[1],[2],[3]])
print("A = \n",A)
print("b = \n",b)
x = np.dot(A.getT(),A)
x = x.getI()

y = np.dot(A.getT(),b)

ans = np.dot(x, y)
print("\n[X,Y] = ", end = "")
for i in ans:
    print("{}".format(i),end="")

A = 
 [[2 0]
 [0 1]
 [2 2]]
b = 
 [[1]
 [2]
 [3]]
[X,Y] = [[ 0.33333333]][[ 1.33333333]]

## Answer 2.

In [31]:
A = np.matrix([[1,-2,4],[1,-1,1],[1,0,0],[1,1,1],[1,4,4]])
b = np.matrix([[0],[0],[1],[0],[0]])
print("A = \n",A)
print("b = \n",b)
x = np.dot(A.getT(),A)
x = x.getI()

y = np.dot(A.getT(),b)

ans = np.dot(x, y)
print("\n[X,Y] = ", end = "")
for i in ans:
    print("{}".format(i),end="")

A = 
 [[ 1 -2  4]
 [ 1 -1  1]
 [ 1  0  0]
 [ 1  1  1]
 [ 1  4  4]]
b = 
 [[0]
 [0]
 [1]
 [0]
 [0]]
[X,Y] = [[ 0.48717949]][[ 0.00854701]][[-0.14529915]]

## Answer 3.

In [32]:
A = np.matrix([[3,-6],[4,-8],[0,1]])
b = np.matrix([[-1],[7],[2]])
print("A = \n",A)
print("b = \n",b)
x = np.dot(A.getT(),A)
x = x.getI()

y = np.dot(A.getT(),b)

ans = np.dot(x, y)
print("\n[X,Y] = ", end = "")
for i in ans:
    print("{}".format(i),end="")

A = 
 [[ 3 -6]
 [ 4 -8]
 [ 0  1]]
b = 
 [[-1]
 [ 7]
 [ 2]]
[X,Y] = [[ 5.]][[ 2.]]